- docker-compose.yml
Need to Setup pmm2-client seperately.
> Setup Server and DB's Docker Compose

- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
- tests/QAN/common_test.js
- tests/QAN/details_test.js
- tests/QAN/overview_test.js
- tests/QAN/pagination_test.js
- tests/QAN/timerange_test.js
- tests/custom_steps.js
- tests/stt/pages/databaseChecksPage.js
- tests/upgradePMM_test.js
- tests/verifyAWSRDSMySQLInstance_test.js
- tests/verifyInsightDashboards_test.js
- tests/verifyMongodbDashboards_test.js
- tests/verifyMysqlDashboards_test.js
- tests/verifyOSDashboards_test.js
- tests/verifyPMMInventory_test.js
- tests/verifyPMMSettingsPageElements_test.js
- tests/verifyPMMSettingsPageFunctionality_test.js
- tests/verifyPostgresqlDashboards_test.js
- tests/verifyRemoteInstances_test.js
- tests/verifyVMDashboards_test.js
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/8290/tests/)
> PMM-7588 Clean up tags

- tests/pages/api/settingsAPI.js
- tests/pages/pmmSettingsPage.js
- tests/pages/testData.js
- tests/stt/allChecks_test.js
- tests/stt/checksExecution_test.js
- tests/stt/databaseChecks_test.js
- tests/stt/pages/allChecksPage.js
- tests/stt/pages/api/perconaServerDB.js
- tests/stt/pages/api/securityChecksAPI.js
- tests/stt/sttSettings_test.js
- tests/upgradePMM_test.js
- tests/verifyPMMInventory_test.js
- tests/verifyPMMSettingsPageFunctionality_test.js
- tests/verifyRemoteInstances_test.js
also included PMM-7830 here. (unskip and fix Communication Settings tests)
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/8363/tests)
> PMM-8005 security checks interval tests

- codeceptConfigHelper.js
- docker-compose.yml
- tests/DbHelpers/perconaServerDB.js
- tests/stt/checksExecution_test.js
- tests/stt/pages/api/perconaServerDB.js
- tests/verifyRemoteInstances_test.js
Ready, changes have been tested on a temp job: https://pmm.cd.percona.com/job/pmm2-ui-tests-temp/469/
Can only be merged along with: 
https://github.com/Percona-Lab/pmm-submodules/pull/1743
https://github.com/Percona-Lab/jenkins-pipelines/pull/953
> PMM-7984 Setting up Docker-Compose for test run

- codeceptConfigHelper.js
- tests/DbaaS/api/dbaasAPI.js
- tests/DbaaS/pages/dbaasActionsPage.js
- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSManageVersion_test.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
- tests/QAN/filters_test.js
- tests/QAN/overview_test.js
- tests/QAN/pages/qanFiltersFragment.js
- tests/QAN/pages/qanOverviewFragment.js
- tests/QAN/timerange_test.js
Tests for Manage Version for DB Clusters
Tests for MongoDB Edit
Tests for Actions verification. 
Tested the code: https://pmm.cd.percona.com/job/pmm2-ui-tests/8492/console
> PMM-7987 Manage Versions DBaaS, Edit Clusters

- .github/workflows/ci.yml
- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/QAN/filters_test.js
- tests/QAN/timerange_test.js
- tests/pages/api/settingsAPI.js
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/8553/pipeline)
> PMM-7974 - create CI workflow

- codeceptConfigHelper.js
- tests/pages/api/amiInstanceAPI.js
- tests/upgradePMM_test.js
Skipped the test for Docker env variable in the upgrade tests
> PMM-8017 changes for AMI upgrade testing 

- tests/pages/pmmSettingsPage.js
- tests/verifyPMMSettingsPageFunctionality_test.js
https://jira.percona.com/browse/PMM-8100
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/8651/tests/
> PMM-8100 DBaaS cannot be disabled with env var

- tests/upgradePMM_test.js
tested [here](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/3442/tests)
> PMM-8024 alerts test after upgrade

- tests/ia/pages/notificationChannelsPage.js
https://github.com/percona-platform/grafana/pull/165
https://github.com/percona-platform/core-ui/pull/9
https://github.com/percona/grafana-dashboards/pull/1238
https://github.com/percona/pmm-server/pull/270
https://github.com/Percona-Lab/pmm-submodules/pull/1840
> PMM-7809 Upgrade Grafana to version 7.5.7

- tests/ia/pages/api/templatesAPI.js
- tests/ia/pagination_test.js
Reverts percona/pmm-ui-tests#43
> Revert "PMM-8273 tests"

- tests/pages/api/addInstanceAPI.js
- tests/remoteInstances/remoteInstancesHelper.js
- tests/upgradePMM_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/9311/pipeline 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/4326/pipeline/
> Fix upgrade tests due to remote instances failure

- codeceptConfigHelper.js
- tests/backup/locations_test.js
- tests/backup/pages/api/backupAPI.js
- tests/backup/pages/api/locationsAPI.js
- tests/backup/pages/inventoryPage.js
- tests/backup/pages/locationsPage.js
- tests/backup/pages/testData.js
- tests/stt/permissions_test.js
- tests/verifyRemoteInstances_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-temp/detail/pmm2-ui-tests-temp/598/pipeline
> PMM-8361 tests for backup locations

- tests/DbaaS/pages/dbaasManageVersionPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/144/tests
> Change PXC operator version back to 1.8.0

- codeceptConfigHelper.js
- tests/.eslintrc
- tests/backup/inventory_test.js
- tests/backup/locations_test.js
- tests/backup/pages/api/backupAPI.js
- tests/backup/pages/inventoryPage.js
- tests/backup/pages/locationsPage.js
- tests/backup/pages/restorePage.js
- tests/backup/pages/testData.js
- tests/helper/mongoDB.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/9979/pipeline
> PMM-8754 mongo backup and restore tests

- tests/backup/scheduled_test.js
- tests/ia/alertRules_test.js
- tests/verifyPMMSettingsPageFunctionality_test.js
- tests/verifyRemoteInstances_test.js
https://pmm.cd.percona.com/job/pmm2-ui-tests/10310/allure/#
> PMM-9005 add check for metrics after adding a remote instance

- tests/pages/adminPage.js
- tests/pages/dashboardPage.js
- tests/pages/remoteInstancesPage.js
- tests/verifyInsightDashboards_test.js
- tests/verifyMongodbDashboards_test.js
- tests/verifyMysqlDashboards_test.js
- tests/verifyOSDashboards_test.js
- tests/verifyPMMDemoDashboards_test.js
- tests/verifyPostgresqlDashboards_test.js
- tests/verifyRemoteInstances_test.js
- tests/verifyVMDashboards_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/756/pipeline
> PMM-9083 add one letter to fix method peformPageDown name

- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
- tests/QAN/pages/qanFiltersFragment.js
- tests/pages/dashboardPage.js
https://pmm.cd.percona.com/job/pmm2-dbaas-e2e-tests/404/allure/
> PMM-T502 PMM-T503 Monitoring Clusters

- testdata/docker-db-setup-scripts/docker_ps_5_7.sh
- testdata/docker-db-setup-scripts/docker_ps_8_0.sh
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/10917/tests
> PMM-8784-Remove-SUPER-from-mysql-priv

- codeceptConfigHelper.js
- tests/dashboards/pages/searchDashboardsModal.js
- tests/dashboards/verifySearchDashboards_test.js
- tests/pages/dashboardPage.js
implemented the dashboards collection verification in the folders
> Pmm 9206 dashboars test

- docker-compose.yml
- tests/DbaaS/pages/dbaasManageVersionPage.js
* PMM-XXXX Remove port 443
* PMM-9050 fix data-qa
> PMM-9050 Fix DbaaS UI component Dataqa (#151)

- package-lock.json
- package.json
- pr.codecept.js
- tests/dashboards/verifySearchDashboards_test.js
- tests/pages/api/grafanaAPI.js
- tests/upgradePMM_test.js
* Includes fixes for dashboards folders test
* introduces new assert plugin due to 'assert' lib issue with crushing allure. see: https://www.screencast.com/t/dUQt02vW
* requires updating dependencies or installing manually: https://www.npmjs.com/package/codeceptjs-chai
> PMM-9243 custom folder and dashboard test

- tests/QAN/timerange_test.js
Verify that changing the time range updates the overview table
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/841/tests
> PMM-8861 added test to verify changing the time range updates the overview table, URL

- tests/QAN/timerange_test.js
The project had already this test, so I rechecked it and added the case number
> PMM-9283 added a number for a previously created case T170

- docker-compose.yml
Reverts percona/pmm-ui-tests#150
> Revert "PMM-XXXX Remove port 443"

- tests/QAN/overview_test.js
- tests/QAN/pages/qanOverviewFragment.js
Added new test for verification of Query on QAN overview table
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/853/
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/860/
> PMM-8865 added new test for case 207 to verify hovering over query in overview table

- tests/ia/alerts_test.js
- tests/ia/pages/api/rulesAPI.js
- tests/ia/ruleTemplates_test.js
https://jira.percona.com/browse/PMM-7781
> PMM-9152: fix rule creation API

- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/515/tests
> Update operators to v1.10.0

- tests/QAN/filters_test.js
- tests/QAN/pages/qanDetailsFragment.js
- tests/QAN/pages/qanFiltersFragment.js
- tests/QAN/pages/qanPaginationFragment.js
- tests/QAN/pagination_test.js
fixed test 390 and added new check to method verifyAvqQueryCount for case 223
And fixed checks in cases 193 and 128 
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/869
> PMM-9295 added new method to click on ShowAllLink with condition of visibility

- tests/upgradePMM_test.js
Verified the changes on upgrade job.
> Pmm 7 fix upgrade

- tests/ia/alertRules_test.js
- tests/ia/pages/alertRulesPage.js
https://jira.percona.com/browse/PMM-9180
> PMM-9180 remove expression/alert from rule modal

- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/603/tests
> updated expected mysql version to recommended

- pr.codecept.js
- tests/pages/homePage.js
- tests/upgradePMM_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests-matrix/detail/pmm2-upgrade-tests-matrix/645/pipeline/
> PMM-9465 check for upgrade logs from file system

- tests/QAN/common_test.js
- tests/QAN/details_test.js
- tests/QAN/filters_test.js
- tests/QAN/overview_test.js
- tests/QAN/pages/qanDetailsFragment.js
- tests/QAN/pages/qanOverviewFragment.js
- tests/pages/dashboardPage.js
added test to verify Plan and PlanID with pg stat monitor and added new method for search in qanOverview
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/949/
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/957/
> PMM-9432 added new test for case T1061 for verifying Plan and PlanID with pg_stat_monitor

- tests/QAN/pages/qanOverviewFragment.js
- tests/QAN/timerange_test.js
Cases:
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1138
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1140
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1141
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1142
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1143
server docker - perconalab/pmm-server-fb:PR-2296-eded043
client docker - perconalab/pmm-client-fb:PR-2296-eded043
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-2296-eded043.tar.gz
Create Staging Instance: https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?DOCKER_VERSION=perconalab/pmm-server-fb:PR-2296-eded043&CLIENT_VERSION=https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-22 …
> PMM-9148 added 5 tests to verify new QAN Copy URL Button works

- tests/backup/pages/inventoryPage.js
- tests/backup/pages/locationsPage.js
- tests/backup/pages/restorePage.js
- tests/backup/pages/scheduledPage.js
- tests/ia/pages/alertRulesPage.js
https://jira.percona.com/browse/PMM-8774
> PMM-8774 fix cell name locators

- .github/workflows/ci.yml
https://github.com/Percona-Lab/pmm-submodules/pull/2356
https://github.com/percona/grafana-dashboards/pull/1315
https://github.com/percona-platform/grafana/pull/353
https://jira.percona.com/browse/PMM-9573
> PMM-9573 Node 16

- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaS_test.js
https://github.com/percona-platform/grafana/pull/350
https://jira.percona.com/browse/PMM-9562
> PMM-9562-PMM-server-IP-warning-grafana8: add test

- tests/ia/pages/iaCommonPage.js
- tests/ia/pagination_test.js
https://github.com/percona-platform/grafana/pull/378
https://jira.percona.com/browse/PMM-9526
> PMM-9526-migrate-enzyme-to-RTL:fix pagination page

- tests/ia/pages/iaCommonPage.js
- tests/ia/pagination_test.js
Reverts percona/pmm-ui-tests#249
> Revert "PMM-9526-migrate-enzyme-to-RTL:fix pagination page"

- tests/ia/pages/iaCommonPage.js
- tests/ia/pagination_test.js
https://github.com/percona-platform/grafana/pull/378
> PMM-95PMM-9526-migrate-enzyme-to-RTL: fix tests

- linksHelper.js
- tests/pages/pmmSettingsPage.js
https://github.com/percona-platform/grafana/pull/400
> fix: change URL for advisors docs

- tests/cli/generic_test.js
- tests/helper/grafana_helper.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/316/pipeline/19
> PMM-9898 Adding tests for yum-cron

- docker-compose.yml
- tests/pages/api/platformAPI.js
- tests/pages/api/settingsAPI.js
- tests/telemetry_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/14704/pipeline
> PMM-9890 add telemetry test

- linksHelper.js
https://github.com/percona-platform/grafana/pull/408
> PMM-9885-advanced-settings-read-more-links-fix: fix link

- tests/portal/portal_test.js
Removed tag post-pmm-upgrade from PMM-T398, since PMM is already connected to the portal and this test will always fail in pipeline
> PMM-7 Removed Tag

- tests/leftNavigation_test.js
- tests/pages/pmmSettingsPage.js
- tests/portal/portal_test.js
- tests/verifyPMMSettingsPageElements_test.js
- tests/verifyPMMSettingsPageFunctionality_test.js
https://jira.percona.com/browse/PMM-9958
> PMM-9958 fix diagnostics button tests

- tests/advisers/stt/databaseChecksTiers_test.js
- tests/advisers/stt/pages/databaseChecksPage.js
- tests/pages/homePage.js
- tests/pages/perconaPlatformPage.js
pmm-ui-tests pipeline:
https://pmm.cd.percona.com/job/pmm2-ui-tests/15050/allure/#suites/a854be2dee5524ab43510364ccf4ce16/bba4fc011ae1ddc6/
Test case:
https://jira.percona.com/secure/Tests.jspa#/testCase/PMM-T1202
> PMM-T1202 Verify that Advisors reflect on user authority / platform role changes

- package-lock.json
- pr.codecept.js
- testdata/docker-cleanup.sh
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/392/pipeline
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests-matrix/detail/pmm2-upgrade-tests-matrix/837/pipeline/60
> PMM-7 New Deps

- tests/DbaaS/api/dbaasAPI.js
- tests/DbaaS/verifyDBaaS_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1024/tests
> fix failing PMM-T969

- tests/advisers/stt/databaseChecksTiers_test.js
- tests/pages/api/portalAPI.js
- tests/portal/portalEntitlements_test.js
- tests/portal/portalTicket_test.js
- tests/portal/portal_test.js
Pipeline run for @portal:
https://pmm.cd.percona.com/job/pmm2-ui-tests/15674/allure/
Pipeline run for @stt:
https://pmm.cd.percona.com/job/pmm2-ui-tests/15676/allure/#suites/a854be2dee5524ab43510364ccf4ce16/b2a357f1e77ec14b/
> Cleanup users and orgs from portal

- tests/upgradePMM_test.js
Reverting back the changes for 15m to 30m because we had some failures, tested on jobs already
> PMM-7 Annotations and Post client upgrade test coverage

- tests/upgradePMM_test.js
https://pmm.cd.percona.com/job/pmm2-ami-upgrade-tests/
> PMM-7 Remove check for AMI

- tests/verifyPMMSettingsPageElements_test.js
Comment broken test until it's fixed
> PMM-9611 comment SSH test

- tests/pages/api/platformAPI.js
- tests/telemetry_test.js
Reverts percona/pmm-ui-tests#301
> Revert "PMM-7 skip telemetry test"

- tests/QAN/common_test.js
- tests/QAN/pages/qanPage.js
- tests/dashboards/pages/searchDashboardsModal.js
> PMM-9943 Add test for dashboard search between QAN and dashboards

- tests/QAN/pages/qanFiltersFragment.js
- tests/QAN/pages/qanPage.js
- tests/verifyAzureMySQLPostgreSQLRemoteInstance_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/19213/tests
> fix failing PMM-T746 PMM-T748

- tests/dashboards/verifyMysqlDashboards_test.js
- tests/pages/dashboardPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1313/tests/
> PMM-7 fix failing PMM-T430 PMM-T317

- docker-compose-clickhouse.yml
- tests/QAN/externalClickhouse_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/840/pipeline/
> PMM-7 Fix clickouse test port

- tests/DbaaS/pages/dbaasPage.js
BEFORE:https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1394/tests
AFTER:https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1397/tests
> PMM-7 fix failing pmm t502

- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1443/tests
> Fix failing PMM-T1130 and PMM-T1158

- tests/DbaaS/verifyDBaaS_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1453/tests
> PMM-7-fix-failing-PMM-T427-PMM-T456

- tests/DbaaS/verifyDBaaS_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1486/tests
> PMM-7-fix-failing-PMM-T969

- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
It can take ~ 5 minutes for Disk Space,RAM,Virtual Memory metrics to show up on Node Summary dashboard. Changing the tests flow to make sure all metrics are loaded before metrics check.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1525/tests
> PMM-7-fix-failing-PMM-T503

- tests/DbaaS/verifyDBaaS_test.js
Skiip because of https://jira.percona.com/browse/PMM-10688
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1555/tests
> PMM-7 fix failing PMM-T547 PMM-T548

- tests/dashboards/verifyMysqlDashboards_test.js
- tests/pages/adminPage.js
- tests/pages/dashboardPage.js
- tests/pages/leftNavMenu.js
- tests/pages/pmmInventoryPage.js
- tests/verifyInsightDashboards_test.js
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/1413/consoleFull
> PMM-7 Fix for Locators for Nightly job Grafana 9

- pr.codecept.js
- tests/helper/apiHelper.js
Mocks api call to user details that contains the product tour flag.
> PMM-10667 Prevent product tour from being visible

- tests/QAN/pages/qanDetailsFragment.js
- tests/pages/homePage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1421/pipeline/
> PMM-7-fix-PMM-T1061-PMM-T334-PMM-T420

- tests/pages/organizationEntitlementsPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-portal-tests/detail/pmm2-upgrade-portal-tests/521/pipeline/
> PMM-7 Fix portal test by changing entitlements row locator

- tests/QAN/filters_test.js
- tests/QAN/pages/qanFiltersFragment.js
- tests/verifyPTSummaryPanels_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1438/tests
> PMM-7 fix failing qan filters

- tests/pages/homePage.js
- tests/upgradePMM_test.js
https://pmm.cd.percona.com/job/pmm2-upgrade-tests/21088/
> PMM-7 Fix upgrade tests 

- tests/configuration/pages/pmmSettingsPage.js
- tests/helper/linksHelper.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/24287/pipeline/
> PMM-7 Fix PMM-T1227

- tests/pages/dashboardPage.js
- tests/pages/remoteInstancesPage.js
- tests/remoteInstances/remoteInstancesHelper.js
- tests/verifyAWSRDSMySQLInstance_test.js
- tests/verifyAWSRDSPostgreSQLInstance_test.js
- tests/verifyAzureMySQLPostgreSQLRemoteInstance_test.js
- tests/verifyTLSMongoDBRemoteInstance_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/1218/pipeline/23/
> PMM-7 Reduce the matrix

- tests/portal/portal_test.js
https://pmm.cd.percona.com/job/pmm2-ui-tests/24570/
> PMM-7 Added @not-ui-pipeline to remaining portal tests

- tests/dockerConfiguration/verifySrvDataDirectory_test.js
Skipping test with bug, making others stable. Three back to back green runs, 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/24758/pipeline/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/24756/pipeline/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/24755/pipeline/
> PMM-7 Fix docker configuration

- tests/DbaaS/api/dbaasAPI.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1820/tests
> PMM-7 fix after db version select move

- tests/DbaaS/pages/dbaasActionsPage.js
- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1863/tests
> PMM-7-fix-register-tests-after-move-from-modal-to-page

- tests/DbaaS/pages/dbaasActionsPage.js
- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSManageVersion_test.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1888/tests
> PMM-7-fix-cluster-tests-after-move-from-modal-to-page

- codeceptConfigHelper.js
- tests/PageObjects/Dashboards/BaseDashboard.js
- tests/PageObjects/Dashboards/Postgresql/ExperimentalPostgresqlDashboards.js
- tests/dashboards/verifyExperimentalPostgresqlDashboards_test.js
Added step to check if correct database is verified.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/25185/pipeline/
> PMM-7: Refactor vacuum test

- tests/configuration/verifyPMMSettingsPageFunctionality_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/26026/tests
> PMM-7-skip-failing-PMM-T782-dbaas-disabled-msg

- tests/DbaaS/pages/dbaasActionsPage.js
- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1981/pipeline/
> PMM-7-olm-change-fixes

- tests/leftNavigation_test.js
- tests/pages/leftNavMenu.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1584/tests
> PMM-7 fix PMM-T433 menu items on sidebar

- tests/pages/testData.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/26984/tests
> PMM-7-fix-PMM-T1338-telemetry-tooltip

- tests/ia/alertRules_test.js
- tests/ia/pages/alertRulesPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/27363/pipeline
> PMM-7-fix-PMM-T1420-create-new-alert-test

- tests/verifyPTSummaryPanels_test.js
Skipping System Summary check for mongo because it doesn't work with latest version
https://jira.percona.com/browse/PMM-11406
> PMM-7-skip-pt-summary-check-for-mongo

- tests/dashboards/verifyMysqlDashboards_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1604/tests/
> PMM-7 Dashboards inside mysql folder tests fix

- tests/dashboards/verifyPostgresqlDashboards_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1605/tests
> PMM-7 Dashboards inside postgresql folder tests fix

- tests/backup/pages/scheduledPage.js
before https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/27919/tests
after https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/27927/tests
> PMM-7-scheduled-backup-verify-values-fix

- tests/pages/testData.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/27937/tests
> PMM-7-telemetry-tooltip-fix

- tests/DbaaS/pages/dbaasActionsPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2093/tests
> PMM-7 dev-latest dbaas fixes

- tests/upgradePMM_test.js
https://pmm.cd.percona.com/job/pmm2-upgrade-tests/25871/
> PMM-7 Fix Test T1505

- tests/DbaaS/pages/dbaasManageVersionPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2407/pipeline
> PMM-7-new-operators-updates

- .github/workflows/pmm-portal-tests.yml
- .github/workflows/pmm-portal-upgrade-tests.yml
- .github/workflows/pmm-ui-tests-upgrade.yml
- .github/workflows/pmm-ui-tests.yml
Portal pipeline - https://github.com/percona/pmm-ui-tests/actions/runs/4501203113/jobs/7921312807
Portal Upgrade pipeline - https://github.com/percona/pmm-ui-tests/actions/runs/4501602967/jobs/7922260966
PMM-ui-tests pipeline - https://github.com/percona/pmm-ui-tests/actions/runs/4501266731/jobs/7921462761
PMM-ui-tests- upgrade pipeline - https://github.com/percona/pmm-ui-tests/actions/runs/4501275948/jobs/7921585526
> PMM-7 Adds health check for the pipelines

- tests/QAN/details_test.js
- tests/QAN/pages/qanFiltersFragment.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1723/tests
> PMM-7 fix flaky details section tabs test

- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/configuration/permissions_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2525/tests
> PMM-9792-no-users-with-empty-pass-pxc-test

- playwright-tests/helpers/CommandLine.ts
- playwright-tests/tests/inventory/inventory.spec.ts
https://github.com/percona/pmm-ui-tests/actions/runs/4722040706
https://github.com/percona/pmm-ui-tests/actions/runs/4722037930
> PMM-7 Fix for the pmm agent location

- tests/DbaaS/pages/dbaasPage.js
- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/DbaaS/verifyDBaaS_test.js
- tests/DbaaS/verifyDbaaSMongoDBCluster_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2534/pipeline/
> PMM-11537 update expose tests

- tests/ia/pages/silencesPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/33706/pipeline/
> PMM-7 fix PMM-T481 new silence button

- cli/tests/mysql.spec.ts
https://github.com/Percona-Lab/pmm-submodules/actions/runs/4859864370/jobs/8663006209
> PMM-7 fix check_metric.sh path

- cli/tests/perconaMySqlServer.spec.ts
https://github.com/Percona-Lab/pmm-submodules/actions/runs/5003217226
> PMM-11309 Fixes issues with the PS cli tests in playwright.

- tests/configuration/pages/pmmInventoryPage.js
- tests/configuration/verifyPMMInventory_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1824/tests
> PMM-7-fix-PMM-T554-PMM-T1226-inventory-tests

- tests/QAN/overview_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1844/tests
> PMM-7-fix-PMM-T412-search-by-query

- cli/helpers/cliHelper.ts
- cli/tests/mongoDb-psmdb.spec.ts
- cli/tests/mongoDb.spec.ts
- cli/tests/mysql.spec.ts
- cli/tests/perconaMySqlServer.spec.ts
- cli/tests/postgreSql-pdpgsql.spec.ts
- cli/tests/postgreSql.spec.ts
Please review and run tests. Thanks.
> PMM-12166 Change check_metric.sh to cli.getMetrics in cli tests

- tests/verifyAnnotations_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1858/tests
> PMM-7-fix-nightly-annotations-tests

- playwright-tests/tests/inventory/components/nodesTable.ts
- playwright-tests/tests/inventory/inventory.spec.ts
https://github.com/percona/pmm-ui-tests/actions/runs/5208785008
> PMM-7 Fix inventory tests

- tests/QAN/filters_test.js
- tests/QAN/pages/qanFiltersFragment.js
Show top 5 link was removed from QAN, now all filters are shown hence removing/updating some tests
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1870/tests
> PMM-7-update-qan-filter-tests

- tests/pages/api/inventoryAPI.js
Fixed  waiting until agent will get to running status
> PMM-7 fixed waiting for agents running status

- tests/ia/alertRules_test.js
- tests/ia/pages/alertRulesPage.js
- tests/ia/pages/testData.js
Note: @ia now needs a setup for this test, addClient=ms,1
jenkins pmm-ui-test(custom) job passed https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/37601/pipeline
>  PMM-T2282 Verfied Alerting is able to monitor for "PMM Agent Down" Automated Test

- tests/metrics/verifyMysqlLogLevel_test.js
- tests/verifyTLSMongoDBRemoteInstance_test.js
- tests/verifyTLSMySQLRemoteInstance_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/2428/pipeline tests fixed
> PMM-7 Paths tests fix for matrix

- cli/tests/generic.spec.ts
runs : https://github.com/Percona-Lab/pmm-submodules/actions/runs/5882037148/job/15951709398
> T1258 : Verify pmm-admin status shows node name

- tests/qa-integration/pmm_ps_integration_test.js
- tests/qa-integration/pmm_pxc_integration_test.js
1) Comment changed locator (not required atm)
2) Update credentials for PXC user
pmm-qa changes : https://github.com/percona/pmm-qa/pull/638
> Fix's for Integration tests in PS, PXC

- tests/configuration/verifyPMMSettingsPageElements_test.js
https://jira.percona.com/browse/PMM-12284
> PMM-12284 Remove Alertmanager settings related test

- tests/pages/api/dumpAPI.js
- tests/pages/dumpPage.js
- tests/verifyDump_test.js
Test Runs: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/43015/pipeline/
> Dump test for sftp upload

- codeceptConfigHelper.js
- tests/administration/serviceAccounts_test.js
- tests/pages/adminPage.js
- tests/pages/administration/serviceAccountsPage.js
- tests/pages/credentials.js
- tests/pages/dashboardPage.js
https://github.com/percona/pmm-qa/actions/runs/8569663295
https://github.com/percona/pmm-qa/actions/runs/8570665240/job/23490495337
> PMM-13040 service account (#768)

- cli/support/types/exec-return.class.ts
- cli/test-setup/docker-compose-pmm-admin-remove.yml
- cli/test-setup/docker-compose-scrape-intervals.yml
- cli/tests/generic.spec.ts
- cli/tests/haproxy.spec.ts
- cli/tests/help.spec.ts
- cli/tests/mongoDb-psmdb.spec.ts
- cli/tests/mysql-conf-file.spec.ts
- cli/tests/mysql.spec.ts
- cli/tests/perconaMySqlServer.spec.ts
- cli/tests/pmm-client-docker.spec.ts
- cli/tests/pmm-server-docker-generic.spec.ts
- cli/tests/pmm-server-only.spec.ts
- cli/tests/postgreSql-pdpgsql.spec.ts
- cli/tests/postgreSql.spec.ts
- cli/tests/proxySql.spec.ts
- cli/tests/remove.spec.ts
- cli/tests/unregister.spec.ts
[Github Test Runs](https://github.com/percona/pmm-qa/actions/runs/8956092582/job/24597487397)
> PMM3 CLI Test Fixes

- tests/dashboards/verifyMysqlDashboards_test.js
- tests/pages/dashboardPage.js
test runs [https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/158/pipeline/78/]
> GR Test Tweaks

- tests/verifyTLSMySQLRemoteInstance_test.js
Test Runs [https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/44835/pipeline]
> Test for PMM-T1896 Verify MySQL -tls-skip-verify works as expected.

- tests/verifyTLSMySQLRemoteInstance_test.js
> Test for PMM-T1896 Verify MySQL -tls-skip-verify works as expected

- tests/pages/components/queryAnalytics/queryAnalyticsFilters.js
- tests/pages/credentials.js
- tests/pages/queryAnalyticsPage.js
- tests/qa-integration/pmm_ps_integration_test.js
https://github.com/percona/pmm-qa/actions/runs/9455525846/job/26045511911
> PMM-11278: Add to the PMM V3

- tests/pages/dashboardPage.js
- tests/qa-integration/pmm_psmdb_integration_test.js
- tests/verifyTLSMySQLRemoteInstance_test.js
Test Runs : https://github.com/percona/pmm-qa/actions/runs/9466064650/job/26076903419
> PMM3 fix arbiter test and ssl test

- cli/tests/unregister.spec.ts
- tests/administration/serviceAccounts_test.js
https://github.com/percona/pmm-qa/actions/runs/9565491235/job/26368545892
https://github.com/percona/pmm-qa/actions/runs/9565348517/job/26368108955
> PMM3 13120: PMM3 Client pmm-admin unregister removes nodes

- playwright-tests/api/okta.api.ts
- playwright-tests/helpers/portal-helper.ts
- playwright-tests/helpers/types/portal-user.class.ts
- playwright-tests/pages/common.page.ts
- playwright-tests/pages/home-dashboard.page.ts
- playwright-tests/pages/page-components/left-navigation-menu.ts
- playwright-tests/pages/page-components/toast-message-modal.ts
- playwright-tests/pages/pmm-settings/percona-platform.page.ts
- playwright-tests/tests/portal/connect-portal.spec.ts
- playwright-tests/tests/portal/portal-connected.spec.ts
- playwright-tests/tests/portal/users-cleanup.spec.ts
https://github.com/percona/pmm-qa/actions/runs/9870489321
> PMM-7 Fix portal tests v3 (#816)

- playwright-tests/api/okta.api.ts
- playwright-tests/helpers/portal-helper.ts
- playwright-tests/helpers/types/portal-user.class.ts
- playwright-tests/tests/portal/connect-portal.spec.ts
- playwright-tests/tests/portal/portal-connected.spec.ts
- playwright-tests/tests/portal/users-cleanup.spec.ts
https://github.com/percona/pmm-qa/actions/runs/9870327412
> PMM-13226: Fix Portal tests

- tests/ia/alertRules_test.js
Fixes failing UI tests on https://github.com/percona/grafana/pull/759.
> PMM-7 Fix no alert rules check

- tests/PageObjects/Dashboards/BaseDashboard.js
- tests/PageObjects/Dashboards/Postgresql/ExperimentalPostgresqlDashboards.js
- tests/dashboards/verifyExperimentalPostgresqlDashboards_test.js
https://github.com/percona/pmm-qa/actions/runs/9891555449/job/27322233712
> PMM-13232: Fix tests with tag @experimental for pmm v3

- tests/qa-integration/pmm_psmdb_integration_test.js
https://github.com/percona/pmm-qa/actions/runs/10403583785
> PMM-7: Fix T1899

- tests/QAN/details_test.js
- tests/QAN/filters_test.js
- tests/QAN/pages/qanFiltersFragment.js
- tests/configuration/pages/pmmInventoryPage.js
- tests/verifyAnnotations_test.js
Test Runs [ https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/2581/tests]
> PMM-13316 Update mongo usage for nightly tests

- tests/dashboards/pages/searchDashboardsModal.js
- tests/pages/dashboardPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/2589/pipeline/
> PMM-7 Fix nightly T1070 and T1086

- tests/dockerConfiguration/pmmClientDockerMultiArch_test.js
- tests/helper/grafana_helper.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests-matrix/detail/pmm2-ui-tests-matrix/3240/pipeline/31/
> PMM-7 Fix multiarch docker tag

- tests/qa-integration/pmm_psmdb_integration_test.js
test runs https://github.com/percona/pmm-qa/actions/runs/10881556850
> Updates Un-Skip Replicaset Lag test

- tests/QAN/timerange_test.js
- tests/pages/adminPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/2723/tests
> PMM-13381: Unskip QAN tests

- tests/QAN/overview_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/328/tests
> PMM-13381: Unskip QAN tests V3

- tests/upgradePMM_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/44571/pipeline/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/44572/pipeline/
> PMM-7: Fix Docker upgrade

- docker-compose-disconnect.yml
- tests/configuration/verifyPMMServerDisconnect_test.js
- tests/pages/dashboardPage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/371/pipeline/
https://github.com/percona/pmm-qa/actions/runs/11157024976/job/31019086924
> P13411: Fix Disconnect tests and stabilize QAN tests for V3

- tests/pages/dashboardPage.js
- tests/qa-integration/pmm_psmdb_integration_test.js
https://github.com/percona/pmm-qa/actions/runs/11179935713
> PMM-13411: Fix for psmdb tests replication and arbiter

- playwright-tests/api/helpers/api-helper.ts
- playwright-tests/pages/page-components/network-tools.ts
- pr.codecept.js
- tests/helper/apiHelper.js
- tests/helper/grafana_helper.js
- tests/pages/api/settingsAPI.js
[PMM-12910](https://perconadev.atlassian.net/browse/PMM-12910) Popup about new version of PMM available
[PMM-12910]: https://perconadev.atlassian.net/browse/PMM-12910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PMM3 fix upgrade tour

- tests/dashboards/verifyHomeDashboards_test.js
- tests/pages/dashboardPage.js
https://pmm.cd.percona.com/job/pmm3-ui-tests-nightly/451/
> PMM-7: Close modal in inghtly

- cli/helpers/cli-helper.ts
- cli/tests/generic.spec.ts
- cli/tests/mysql-conf-file.spec.ts
- cli/tests/pmm-client-docker.spec.ts
- cli/tests/pmm-server-only.spec.ts
- cli/tests/proxySql.spec.ts
- cli/tests/remove.spec.ts
- tests/remoteInstances/remoteInstancesHelper.js
qa integration PR: https://github.com/Percona-Lab/qa-integration/pull/83
test runs: https://github.com/percona/pmm-qa/actions/runs/11668917088/job/32489684776
> PMM-13506 pmm3 fix cli integration tests

- tests/configuration/verifyPMMSettingsPageFunctionality_test.js
- tests/pages/api/settingsAPI.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/502/tests
> PMM-7: Fix for the T486

- tests/qa-integration/pmm_ps_integration_test.js
https://github.com/percona/pmm-qa/actions/runs/11892574312
> PMM-7: Fix ps integration

- tests/metrics/verifyMongoDBCollectionFlags_test.js
- tests/pages/api/grafanaAPI.js
https://github.com/percona/pmm-qa/actions/runs/12081114026
> Pmm2 fix mongoexporter

- tests/DbaaS/verifyDBaaSPXCCluster_test.js
- tests/configuration/verifyPMMSettingsPageFunctionality_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/580/tests/
> PMM-13537: Unskip test to set up pmm url in settings

- docker-compose.yml
- playwright-tests/docs/setup-env-portal.md
Updates files to use the correct environment variable for portal url.
Related PRs:
- https://github.com/percona/pmm/pull/3382
- https://github.com/percona/grafana/pull/792
> PMM-13569 Portal url env variable

- docker-compose.yml
- tests/qa-integration/pmm_psmdb_integration_test.js
- tests/upgradePMM_test.js
* PMM-7: debug
* PMM-7: adds settings and dashboard tests
> PMM-13733: PMM Migration v2

- tests/QAN/overview_test.js
- tests/configuration/verifyPMMInventory_test.js
- tests/verifyPTSummaryPanels_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/710/pipeline/
> PMM-7: Fixes for nightly v3

- tests/verifyAuroraRemoteInstance_test.js
- tests/verifyAzureMySQLPostgreSQLRemoteInstance_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/51103/tests
> PMM-7: Fix datatable v2

- tests/configuration/verifyPMMSettingsPageFunctionality_test.js
- tests/verifyAWSRDSMySQLInstance_test.js
- tests/verifyAnnotations_test.js
- tests/verifyAuroraRemoteInstance_test.js
- tests/verifyAzureMySQLPostgreSQLRemoteInstance_test.js
- tests/verifyRemoteInstances_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests/detail/pmm3-ui-tests/2786/tests
> Pmm 7 fix datatable

- tests/dashboards/pages/homeDashboard.js
- tests/dashboards/verifyHomeDashboards_test.js
- tests/pages/api/inventoryAPI.js
- tests/pages/dashboardPage.js
- tests/pages/homePage.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/742/pipeline/
> PMM-13770: PMM-T2007 - Verify Monitored DB Services panel on home dashboard

- tests/QAN/externalClickhouse_test.js
- tests/configuration/verifyPMMServerDisconnect_test.js
- tests/helper/grafana_helper.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests/detail/pmm3-ui-tests/3181/pipeline/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests/detail/pmm3-ui-tests/3182/pipeline/
> PMM-7: Fix cookie issue

- tests/dashboards/pages/searchDashboardsModal.js
- tests/upgrade/dashboards_test.js
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-upgrade-test-runner/detail/pmm3-upgrade-test-runner/1140/pipeline/
> PMM-13481: Custom dashboard upgrade tests

- tests/qa-integration/pmm_ps_integration_test.js
https://github.com/Percona-Lab/qa-integration/actions/runs/13963638647/job/39089346738
> PMM3 fix ps auth test

- tests/QAN/details_test.js
- tests/pages/components/queryAnalytics/queryAnalyticsQueryDetails.js
https://github.com/percona/pmm-qa/actions/runs/14079889370/job/39433724935
> PMM-13636: PMM QAN is Broken when Query having Explain Keyword

- docker-compose-clickhouse.yml
- docker-compose-external-pg-ssl.yml
- docker-compose-external-pg.yml
- tests/QAN/externalClickhouse_test.js
- tests/dashboards/verifyNodesOverviewDashboard_test.js
- tests/dockerConfiguration/externalPostgres_test.js
- tests/dockerConfiguration/publicAddressVariable_test.js
- tests/dockerConfiguration/verifySrvDataDirectory_test.js
- tests/helper/grafana_helper.js
- tests/pages/explorePage.js
- utils/external-pgsql-ssl-config.cnf
https://github.com/percona/pmm-qa/actions/runs/14307952710/job/40114344187
> PMM-13171: External PGSQL and Clickhouse, and other docker tests if fb testing. (#963)

- cli/tests/help.spec.ts
Updated all occurrences of "TLS certificates validation" to "TLS certificate verification" for better clarity and consistency in help text. This improves user understanding of TLS-related options
> PMM-13887 Update TLS help text for consistent and accurate wording
