tests/pages/remoteInstancesPage.js
tests/verifyAWSRDSMySQLInstance_test.js

Adds test to check that is possible to discover RDS instances without credentials. It returns an error since IAM roles are not defined but it proves that discovery is possible.
https://github.com/percona/pmm-doc/pull/579
https://github.com/percona-platform/grafana/pull/221
https://github.com/Percona-Lab/pmm-submodules/pull/1969

PMM-7690 Discovery based on IAM roles

---

tests/DbaaS/pages/dbaasActionsPage.js
tests/DbaaS/pages/dbaasPage.js
tests/DbaaS/verifyDBaaSPXCCluster_test.js
tests/DbaaS/verifyDbaaSMongoDBCluster_test.js

- Adds e2e tests for update DB cluster
- Changes column _Database Type_ to _Database_ in DB clusters table
- Adds version to _Database_ column
If we end up having problems because we are using the recommended database version to create the cluster and checking for a hardcoded version we will have to force the creation of cluster to a specific version. It is already allowed by `createClusterBasicOptions` and `createClusterAdvancedOption`.
https://github.com/percona-platform/grafana/pull/228
https://jira.percona.com/browse/PMM-8167

PMM-8167 Update DB Cluster version

---

tests/DbaaS/pages/dbaasPage.js
tests/verifyPMMSettingsPageFunctionality_test.js

Removing check of grafana error Service dbaas.v1beta1.Components is disabled. which is now shown anymore
Test green: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/10821/tests

PMM-8461-fix-failed-ui-test

---

tests/pages/dashboardPage.js
tests/verifyMysqlDashboards_test.js

Test case 1070 is the same as test case 449 with the difference only in the start page and the name of the metric. I added the data provider to the 1070 case so as not to duplicate the code.
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/861/

PMM-8866 edited test-case 1070 to verify share link on Home Dashboard for case 449

---

tests/remoteInstances/remoteInstancesHelper.js

MongoDB tests had been disabled due to issue with MongoDB exporter version used in our test pipeline. Now that it has been fixed, MongoDB related UI tests should be renabled.
Related PRs:
- https://github.com/Percona-Lab/pmm-submodules/pull/2310

PMM-9445 Enable MongoDB UI tests

---

tests/advisers/stt/sttSettings_test.js
tests/verifyPMMSettingsPageFunctionality_test.js

https://github.com/percona-platform/grafana/pull/349
temporary disabling of tags, due to problems with the assembly of branches inherited from main

PMM-9237-re-enabling-tests-migrate-from-enzyme-grafana8: remove tags

---

tests/DbaaS/pages/dbaasActionsPage.js
tests/DbaaS/verifyDBaaS_test.js

"Create DB Cluster" button is disabled for ~1 second and tests were failing because of this
Existing failures unrelated
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1008/tests

PMM-7 Fix failed tests due to disabled create button

---

tests/pages/api/portalAPI.js

We made a change in service now creation, to be able to distinguish ui tests users in logs and okta, this PR handles that change.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/15645/pipeline/

Fix new email service now

---

tests/portal/portal_test.js

This PR fixes pmm2-portal-upgrade job, issue was that org id was not define when post upgrade tests were running
pipelines resuls:
https://pmm.cd.percona.com/job/pmm2-upgrade-portal-tests/8/
https://pmm.cd.percona.com/job/pmm2-ui-tests/15871/

PMM-7 Fix for pmm portal upgrade pipeline

---

tests/pages/api/portalAPI.js

Okta call to delete user needs to be made twice to delete user, first call just deactivates user. This PR fixes this issue.

PMM-7 Fix for deletion of portal users

---

tests/DbaaS/verifyDBaaSPXCCluster_test.js

This fixes all "Expected DB Type was MySQL 8.0.25, but found MySQL 8.0.27" failed tests
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1344/tests

PMM-7 fix failing mysql version

---

tests/DbaaS/pages/dbaasActionsPage.js

All tests containing "Expected the k8s Cluster DB Cluster Name to show pxc-dbcluster-iduf4d but found mysql-rj4oi7" broke after https://jira.percona.com/browse/PMM-10182. This PR replaces the generated cluster names.
before: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1429/tests
after: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1433/tests

PMM-10531 fix-failing-db-cluster-names

---

tests/DbaaS/pages/dbaasActionsPage.js
tests/DbaaS/verifyDBaaSPXCCluster_test.js
tests/DbaaS/verifyDbaaSMongoDBCluster_test.js

Deleting PSMDB clusters in pending can be too quick (or UI too slow) so the DELETING status won't appear and it's causing failures. This PR fixes it.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1462/tests/

PMM-7-fix-failing-delete-pending-clusters

---

tests/DbaaS/pages/dbaasPage.js
tests/DbaaS/verifyDBaaSPXCCluster_test.js
tests/pages/dashboardPage.js

Test were failing randomly because some metrics might not have been available in selected time range for second or third run.
Tests using "cluster" filter were moved to a separate scenario - they need to be run only once (there's only one cluster) not three times as it was before.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1480/tests

PMM-7-fix-pxc-monitoring

---

tests/DbaaS/pages/dbaasPage.js
tests/DbaaS/verifyDbaaSMongoDBCluster_test.js

Changing time range to "Last 15 minutes" to avoid random failures when metric is not available on the dashboard anymore at the time of xth run. Also moving tests related to cluster to a separate scenario to run them only once.
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/1483/tests

PMM-10623 fix psmdb monitoring

---

tests/ia/alertRules_test.js
tests/ia/pages/alertRulesPage.js

Reverts percona/pmm-ui-tests#453
Merged too soon and is blocking other PRs.
Currently there's another UI test that is block the grafana update. (Locally all tests pass, on CI if fails)

Revert "PMM-10881 Change "Edit folder" to "Go to folder""

---

tests/DbaaS/pages/dbaasPage.js
tests/DbaaS/verifyDBaaSPXCCluster_test.js
tests/DbaaS/verifyDBaaS_test.js
tests/DbaaS/verifyDbaaSMongoDBCluster_test.js

This PR fixes test cases PMM-T1571 and PMM-T1577
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2358/tests
- removing disabled elements because they are not on edit page anymore,
- changing source range count behaviour

PMM-11428-broken-edit-page-fix

---

tests/configuration/verifyPMMSettingsPageFunctionality_test.js
tests/pages/leftNavMenu.js

* Verify at the beginning of the test case that BM is enabled by default 
* Verify that the BM toggle is on the Advance settings page by default.
* Verify that the BM icon is visible on the homepage.

PMM-11640 backup management enabled by default

---

tests/DbaaS/verifyDBaaS_test.js

Changing the order of tooltips because the lower tooltip icon is hides under the upper tooltip on mouse hover
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-dbaas-e2e-tests/detail/pmm2-dbaas-e2e-tests/2594/pipeline/

PMM-7 fix PMM-T1512 aws key tooltip

---

tests/configuration/verifyPMMSettingsPageFunctionality_test.js

The cause of PMM-T486 - Verify Public Address in PMM Settings 502 Bad Gateway failures seems to be a test that run before (PMM-T1328 Verify public address is set automatically on Percona Platform page once connected to Portal) - Grafana restarts every time when a public address is changed after PMM is connected with Portal so moving the Portal test to the bottom as a workaround.
Looks stable now, 3 success runs in row:
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1812/tests/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1811/tests/
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1810/tests

PMM-7-fix-PMM-T486-settings-public-address

---

.github/workflows/pmm-upgrade-ui-tests-matrix-full.yml
.github/workflows/pmm-upgrade-ui-tests-matrix.yml
.github/workflows/pmm-upgrade-ui-tests.yml
.github/workflows/pmm-version-getter.yml

Required to fix upgrade to version string for scheduled jobs:
* Added reusable workflow to detect latest versions sting to avoid code duplication.
* Fixed matrix generator for "upgrade to release version" choice

PMM-7 added reused get version job

---

.github/workflows/pmm-upgrade-ui-tests-matrix-full.yml
.github/workflows/pmm-upgrade-ui-tests-matrix.yml
.github/workflows/pmm-upgrade-ui-tests.yml
.github/workflows/upgrade-tests-pipeline.yml

https://github.com/percona/pmm-ui-tests/actions/runs/5762918673/job/15623643736

PMM-12359 podman way upgrade

---

tests/pages/adminPage.js
tests/pages/remoteInstancesPage.js
tests/verifyTLSPostgresRemoteInstance_test.js

https://github.com/percona/pmm-qa/actions/runs/9969342391

PMM-13232 Fix SSL postgres for v3

---

tests/qa-integration/pmm_pdpgsql_integration_test.js
tests/qa-integration/pmm_ps_integration_test.js
tests/qa-integration/pmm_psmdb_integration_test.js
tests/qa-integration/pmm_pxc_integration_test.js

PXC: https://github.com/Percona-Lab/qa-integration/actions/runs/10130066920
PS: https://github.com/Percona-Lab/qa-integration/actions/runs/10130069041
PDPGSQL: https://github.com/Percona-Lab/qa-integration/actions/runs/10038716413
Setup PR: https://github.com/Percona-Lab/qa-integration/pull/73

PMM-13240 PMM3 integration ui test fixs

---

tests/verifyTLSMongoDBRemoteInstance_test.js

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests/detail/pmm3-ui-tests/461/pipeline/90/

PMM-13491Updates to fix mongo ssl ui test

---

tests/metrics/verifyMongoDBCollectionFlags_test.js
tests/pages/api/grafanaAPI.js

test runs : https://github.com/percona/pmm-qa/actions/runs/11939079410/job/33278809308

updates, fix flaky test, use service_id instead and fix prev merge issue.

---

tests/verifyTLSPostgresRemoteInstance_test.js

updates, fix test to verify only pdpgsql 16 for now
test runs https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests/detail/pmm3-ui-tests/824/pipeline

updates, fix test to verify only pdpgsql 16 for now

---

tests/qa-integration/pmm_pdpgsql_integration_test.js
tests/qa-integration/pmm_ps_integration_test.js
tests/qa-integration/pmm_pxc_integration_test.js

PS: [https://github.com/Percona-Lab/qa-integration/actions/runs/12231594921/job/34114961054 ( fix 1 know failure)](https://github.com/Percona-Lab/qa-integration/actions/runs/12250389432)
PXC: https://github.com/Percona-Lab/qa-integration/actions/runs/12237833515
PDPGSQL: https://github.com/Percona-Lab/qa-integration/actions/runs/12231618647

PMM3 13601 Fix QA-integration tests

---

tests/helper/grafana_helper.js
tests/pages/homePage.js
tests/product-tour/productTour_test.js

Fixes product tour test failures due to the update modal appearing.
Once PMM-13608 is fixed it would be better to disable updates through settings rather than to rely on the snoozed pmm version.
Related: https://github.com/percona/grafana/pull/791

PMM-7 Fix product tour tests

---

tests/advisors/pages/api/advisorsAPI.js
tests/configuration/permissions_test.js
tests/configuration/verifyPMMSettingsPageFunctionality_test.js
tests/dashboards/pages/homeDashboard.js

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/791/pipeline

PMM-13826: 'PMM-T2009 - Verify that editor user can see failed advisors data on home dashboard @nightly
